input {
  http {
    port => 8080
    host => "0.0.0.0"  # Bind to all network interfaces
  }
}

filter {
  # Create the desired structure
  ruby {
    code => '
      event.set("message", event.get("message").to_json) if event.get("message")
    '
  }

  # Remove unwanted fields like host.ip, url, http.request, etc.
  mutate {
    remove_field => ["@version", "event", "user_agent", "http", "url", "host"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch.util:9200"]
    index => "data-util-test-stream-%{+YYYY.MM.dd}"
    #user => "elastic"
    #password => "changeme"
  }
  stdout {
    codec => rubydebug
  }
}
