FROM postgres:17.0
LABEL authors="Witold Krak"
LABEL email="witold.krak@gmail.com"

# Set the default user to 'postgres' instead of 'root'
USER postgres

# Expose the default port for Postgres (5432 is standart Postgres port)
EXPOSE 50001
