version: "2"
services: 
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    image: elasticsearch.util
    environment: 
      - "discovery.type=single-node" 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" 
    ports: 
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./elasticsearch/data:/usr/share/elasticsearch/data"
    networks:
      - "util"
    restart: "no"
    container_name: "elasticsearch.util"

  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    image: "logstash.util"
    ports: 
      - "5044:5044"
      - "9600:9600"
      - "8080:8080"
    volumes: 
      - "./logstash/pipeline:/usr/share/logstash/pipeline/"
    networks:
      - "util"
    restart: "no"
    container_name: "logstash.util"

  kibana:
    build:
      context: ./kibana
      dockerfile: Dockerfile
    image: "kibana.util"
    environment: 
      - "ELASTICSEARCH_HOSTS='http://elasticsearch.util:9200'"
    ports:
      - "5601:5601"
    networks: 
      - "util"
    restart: "no"
    container_name: "kibana.util"


networks:
  util:
    driver: "bridge"
