version: "2"
services: 
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    image: elasticsearch.util
    environment: 
      - "discovery.type=single-node" 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" 
    ports: 
      - "50010:9200"
      - "50011:9300"
    volumes:
      - "elasticsearch.util:/usr/share/elasticsearch/data"
    networks:
      - "util"
    restart: "no"
    container_name: "elasticsearch.util"

  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    image: "logstash.util"
    ports: 
      - "50020:5044"
      - "50021:9600"
      - "50022:8080"
    volumes: 
      - "./logstash/pipeline:/usr/share/logstash/pipeline/"
    networks:
      - "util"
    restart: "no"
    container_name: "logstash.util"

  kibana:
    build:
      context: ./kibana
      dockerfile: Dockerfile
    image: "kibana.util"
    environment: 
      - "ELASTICSEARCH_HOSTS='http://elasticsearch.util:50030'"
    ports:
      - "50030:5601"
    networks: 
      - "util"
    restart: "no"
    container_name: "kibana.util"


networks:
  util:
    driver: "bridge"

volumes:
  elasticsearch.util:
